[package]
name = "kyusin-bots"
description = "Bot per game KyuSin, dengan level kesulitan."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
cozy-chess.workspace = true
kyusin-core.workspace = true
kyusin-games.workspace = true
serde_json.workspace = true
