/**
 * Tiruan backend hanya untuk `npm run dev` di peramban biasa (tanpa Tauri),
 * supaya tampilan bisa dicek cepat (SPEC §11). Isinya meniru data game
 * fixture dari Rust, termasuk dua bahasa; aturan yang sebenarnya tetap di
 * Rust dan diuji di sana. Tidak ikut build produksi.
 */

import type { AppInfo, Category, Step, TutorialState } from './backend';
import type { Localized } from './i18n.svelte';

const steps: Step[] = [
	{
		teks: {
			id: 'Ada 7 batang. Setiap giliran kamu boleh mengambil 1 sampai 3.',
			en: 'There are 7 sticks. Each turn you may take 1 to 3.'
		},
		sebelum: [],
		aksi: null,
		sorot: [],
		petunjuk: null
	},
	{
		teks: { id: 'Ambil 3 batang supaya tersisa 4.', en: 'Take 3 sticks so that 4 are left.' },
		sebelum: [],
		aksi: 'take 3',
		sorot: ['aksi:take 3'],
		petunjuk: {
			id: 'Pilih tombol yang mengambil tiga batang.',
			en: 'Choose the button that takes three sticks.'
		}
	},
	{
		teks: {
			id: 'Lawan mengambil 1, tersisa 3. Ambil semuanya untuk menang.',
			en: 'Your opponent took 1, leaving 3. Take them all to win.'
		},
		sebelum: ['take 1'],
		aksi: 'take 3',
		sorot: ['aksi:take 3'],
		petunjuk: {
			id: 'Batang terakhir menang: ambil ketiganya.',
			en: 'The last stick wins: take all three.'
		}
	},
	{
		teks: {
			id: 'Kamu mengambil batang terakhir dan menang.',
			en: 'You took the last stick and won.'
		},
		sebelum: [],
		aksi: null,
		sorot: [],
		petunjuk: null
	}
];

let index = 0;
let left = 7;

function text(): Localized {
	const sticks = Array.from({ length: left }, () => '│').join(' ');
	const won = left === 0;
	return {
		id: `Batang tersisa: ${left}\n\n  ${sticks}\n\n${won ? 'Kamu menang.' : 'Giliranmu.'}`,
		en: `Sticks left: ${left}\n\n  ${sticks}\n\n${won ? 'You win.' : 'Your turn.'}`
	};
}

function state(feedback: TutorialState['feedback'] = null): TutorialState {
	const step = steps[index] ?? null;
	const max = Math.min(3, left);
	return {
		game: 'fixture',
		title: { id: 'Batang: dasar', en: 'Sticks: basics' },
		index,
		total: steps.length,
		finished: index >= steps.length,
		step,
		view_text: text(),
		actions: step?.aksi
			? [
					{
						spec: {
							kind: 'template',
							verb: 'take',
							params: [{ name: 'n', type: 'int', min: 1, max, step: 1 }]
						},
						usage: 'take <n>',
						concrete: Array.from({ length: max }, (_, i) => `take ${i + 1}`)
					}
				]
			: [],
		feedback
	};
}

function enter() {
	for (const c of steps[index]?.sebelum ?? []) left -= Number(c.split(' ')[1]);
}

const unknown = (id: string): Localized => ({
	id: `Tidak ada game \`${id}\`.`,
	en: `No game \`${id}\`.`
});

export const devApi = {
	app_info: async (): Promise<AppInfo> => ({ name: 'KyuSin', version: '0.1.0-dev' }),
	catalog: async (): Promise<Category[]> => [
		{
			key: 'uji',
			label: { id: 'Uji (fixture)', en: 'Test (fixture)' },
			games: [
				{
					id: 'fixture',
					nama: { id: 'Fixture: Batang', en: 'Fixture: Sticks' },
					kategori: 'uji',
					pemain_min: 2,
					pemain_maks: 2,
					jenis: 'giliran',
					lawan: 'bot',
					kompetitif: false,
					lan: false,
					agen: false,
					rtp: null,
					tutorial: 'crates/games/src/fixture/tutorial.toml',
					perintah: [
						{
							pola: 'take <n>',
							ringkas: { id: 'Ambil 1 sampai 3 batang', en: 'Take 1 to 3 sticks' }
						}
					],
					rtp_line: null
				}
			]
		}
	],
	man: async (id: string): Promise<Localized> => {
		if (id !== 'fixture') throw unknown(id);
		return {
			id: 'NAMA\n    Fixture: Batang (fixture)\n\n(tiruan dev; halaman man asli dibangkitkan Rust)\n\nPERINTAH\n    take <n>  Ambil 1 sampai 3 batang\n',
			en: 'NAME\n    Fixture: Sticks (fixture)\n\n(dev mock; the real man page is generated by Rust)\n\nCOMMANDS\n    take <n>  Take 1 to 3 sticks\n'
		};
	},
	tutorial_start: async (id: string): Promise<TutorialState> => {
		if (id !== 'fixture') throw unknown(id);
		index = 0;
		left = 7;
		enter();
		return state();
	},
	tutorial_act: async (command: string): Promise<TutorialState> => {
		const step = steps[index];
		if (!step?.aksi)
			return state({
				kind: 'wrong',
				hint: {
					id: 'Langkah ini hanya bacaan; pilih [ LANJUT ].',
					en: 'This step is reading only; choose [ NEXT ].'
				}
			});
		if (command.trim().split(/\s+/).join(' ') !== step.aksi)
			return state({ kind: 'wrong', hint: step.petunjuk ?? { id: '', en: '' } });
		left -= Number(step.aksi.split(' ')[1]);
		index += 1;
		enter();
		return state({ kind: 'correct' });
	},
	tutorial_next: async (): Promise<TutorialState> => {
		index += 1;
		enter();
		return state();
	},
	tutorial_stop: async (): Promise<void> => {}
};
